### ISSUE TITLE
Append behavior is prepend?

### ISSUE THREAD

**Issue by posener** [go4org/mem#1]
Hey,
I would expect that `a.Append(b)` will return b appended after a, same as `a = append(a, b...)`. I think that the current implementation is doing the other way around.

But maybe this is only me :smile:

**Comment by bradfitz** [comment]
I agree the docs are lacking (there are no docs), but I did name the parameter `dst`, not `a` or `b`.

e.g. https://golang.org/pkg/strconv/#AppendBool & friends

**Comment by puellanivis** [comment]
I had considered this as well, and thought that a more useful name might be `AppendTo`.

In the case of all of the `strconv.AppendXY` cases, there is an additional second argument providing the source. The semantics of `dst = src.Append(dst)` ends up with the `src` and `dst` in an order that is swapped from what we normally would expect.

But using an analogous form to `src.WriteTo(dst)` from `io.WriterTo`, the order and behavior of the function is now more apparent in the function name.

**Comment by bradfitz** [comment]
We could just move Append to be a package-level func instead of a method.

Thoughts, @puellanivis @posener?

**Comment by puellanivis** [comment]
Package-level also works.

**Comment by posener** [comment]
I don't have a strong opinion.
I agree that with the current implementation the code without the documentation is not clear.

**Comment by bradfitz** [comment]
FWIW it's since been documented from when I originally closed this bug (https://godoc.org/go4.org/mem#RO.Append)

**Comment by posener** [comment]
I meant that when you read a code that uses the function and not digging into the doc, it is not clear. Reading `a.Append(b)` doesn't say if a is appended to b or vice versa.

**Comment by bradfitz** [comment]
Changed. Yay v0.
